# Generated by Django 5.2.4 on 2025-07-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=1000, unique=True)),
                ('room_name', models.CharField(max_length=1000)),
                ('insession', models.BooleanField(default=True)),
            ],
        ),
    ]
